[package]
name = "xmysql"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
sqlx = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
tokio = {workspace = true,features = ["full"]}
