[package]
name = "xredis"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
redis = { workspace = true }
r2d2 = { workspace = true }
tokio = { workspace = true }
