[package]
name = "crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
# crypto
aes = { workspace = true }
cbc = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
